### ISSUE TITLE
When running the tests: Cannot read property 'createElement' of undefined

### ISSUE THREAD

**Issue by hschaeidt** [react-component/notification#39]
This library causes the test-suite to fail. It is probably due to the `jsdom` environment, which does not allow by default executing scripts like `document.createElement()`.

See https://github.com/jsdom/jsdom#executing-scripts for more information.

The `rc-notification` being a peer dependency of `antd: ^3.0.0` in my case.

Stacktrace:
```
node node_modules/react-scripts-ts/scripts/test.js --runInBand --env=jsdom
node_modules/react-scripts-ts/scripts/test.js:22
  throw err;
  ^

TypeError: Cannot read property 'createElement' of undefined
    at Function.newNotificationInstance [as newInstance] (node_modules/antd/node_modules/rc-notification/lib/Notification.js:180:20)
    at getMessageInstance (node_modules/antd/lib/message/index.js:34:33)
    at notice (node_modules/antd/lib/message/index.js:65:5)
    at Object.error (node_modules/antd/lib/message/index.js:97:16)
    at src/components/form/input/CustomSelect.tsx:30:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

Process finished with exit code 1
```

**Comment by hschaeidt** [comment]
fixed by upgrading antd to 3.3.1
