### ISSUE TITLE
document is not defined on server side render

### ISSUE THREAD

**Issue by davidfurlong** [react-component/notification#42]
Guessing this library doesn't support SSR?

```
Unhandled Rejection at: Promise {
  <rejected> ReferenceError: document is not defined
    at Function.newNotificationInstance [as newInstance] (/Users/Dave/Projects/deedmob/client/node_modules/rc-notification/lib/Notification.js:176:13)
    at getNotificationInstance (/Users/Dave/Projects/deedmob/client/node_modules/antd/lib/notification/index.js:96:33)
    at Object.notice [as open] (/Users/Dave/Projects/deedmob/client/node_modules/antd/lib/notification/index.js:128:5)
    at Object.api.(anonymous function) [as success] (/Users/Dave/Projects/deedmob/client/node_modules/antd/lib/notification/index.js:178:20)
    at /Users/Dave/Projects/deedmob/client/build/webpack:/src/helpers/responseHandler.js:58:18
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) } reason: ReferenceError: document is not defined
    at Function.newNotificationInstance [as newInstance] (/Users/Dave/Projects/deedmob/client/node_modules/rc-notification/lib/Notification.js:176:13)
    at getNotificationInstance (/Users/Dave/Projects/deedmob/client/node_modules/antd/lib/notification/index.js:96:33)
    at Object.notice [as open] (/Users/Dave/Projects/deedmob/client/node_modules/antd/lib/notification/index.js:128:5)
    at Object.api.(anonymous function) [as success] (/Users/Dave/Projects/deedmob/client/node_modules/antd/lib/notification/index.js:178:20)
    at /Users/Dave/Projects/deedmob/client/build/webpack:/src/helpers/responseHandler.js:58:18
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by davidfurlong** [comment]
I suppose dispatching a new notification on the server is expected to fail.

**Comment by iyobo** [comment]
The cleanest way is to make all references to `document` be `global.document` instead so as to avoid runtime problems.

This is an issue when using antd and nextJS SSR
